query homePage($filter: PostsFilter) {
  page(relativePath: "home.mdx") {
    ...PageParts
  }

  settings(relativePath: "settings.json") {
    logo
    menuItems {
      label
      link
    }
  }

  postsConnection(sort: "date", filter: $filter, last: 5) {
    edges {
      node {
        title
        date
        id
        protected
        password
        _sys {
          filename
        }
      }
    }
  }

  projectsConnection {
    edges {
      node {
        date
        type
        title
        description
        link
        image
      }
    }
  }
}
